version: 0.2

phases:
  install:
    commands:
      # install dependencies
      - npm install
      - npm run client-install

      # Upgrade aws CLI to the latest version
      - pip install --upgrade awscli
  
  build:
    commands:
      - npm run client-build


