version: 0.2

phases:
  install:
    commands:
      # install dependencies
      - npm install
      - npm run client-install
      - npm run client-build

      # Upgrade aws CLI to the latest version
      - pip install --upgrade awscli

